### PR TITLE
fix: WP-89 - allow optional other type of SectionCardList

### PR DESCRIPTION
**Pull request by garySiladi**
This is a fix for the component-sections-card regarding the task WP-89 https://jira.economist.com/browse/WP-89 . It needs to be accompanied by changes in fe-blogs.

### CODE REVIEW

**Comment by umbobabo** [comment]
I don't think we are going in the right direction with this component. For sure is not @garySiladi fault but it is due to the initial approach to the component.
The component is too customised and not reusable at all.
My suggestion is that this component could be refactored in a more composable way or we should deprecate it and move it inside the product directly because doesn't have sense having this in a separate repo. It just increase the time for release a change.

Ideally we should review this component similarly to this:
https://github.com/economist-components/component-newsletter-subscription/blob/master/src/example.js

The advantage of this approach are different:
* You can apply classname in the composition so you can easily achieve BEM
* The component is anyway atomic because the sub-part of the composition should be thought to work togheter.
* The composition permit you to easily alternate sub-part of the component with external elements/components.

What do you think @garySiladi @yasgreen93 @tomiberes @varholak-peter.

**Comment by garySiladi** [comment]
@umbobabo Yes, the actual structure of this component is hardly scalable and too specific at parts, but that can also be said about other economist components. If our goal is to develop such components that can be used by anyone, than we should look into the structure of many of our components. In that case we could set this as our goal for the future.

**Comment by varholak-peter** [comment]
copypasterino: "What do we consider reusable? In the context of using it on E.com, all economist products or so reusable that some other person can use it in their own project?"

**Comment by umbobabo** [comment]
Our components are OpenSource and we are happy if someone want to use these components, but our may driver to the components approach is to having them reusable across our products.
Obviously we don't have infinite resources in term of developers so review every components to make it better is not applicable and not necessary because not all the component deserve to be keep up to date.
In this case I think that the component will be soon re-used on other product and I think is a good exercise start to review this component to be more data agnostic (removing hardcode values mapped for data) and more composable (that also help about BEM).
Anyway, the general current approach is that a new component could be developed inside the product directly and move to an external repo when another product need to use it.
In this case the component is already in an external repo so it doesn't make sense to move inside fe-blogs if we think that in the future this component can be used by other product.

**Comment by umbobabo** [comment]
I talked with Jay, we merge this PR and open another one to refactor this component.

**Pull request merged**
